# Generated by Django 5.0.1 on 2025-10-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="default_bridge",
            field=models.CharField(
                default="vmbr0",
                help_text="Default network bridge for containers",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_cpu_cores",
            field=models.IntegerField(
                default=2,
                help_text="Default number of CPU cores for new LXC containers",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_disk_gb",
            field=models.IntegerField(
                default=20, help_text="Default disk size in GB for new LXC containers"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_dns_primary",
            field=models.GenericIPAddressField(default="8.8.8.8", help_text="Primary DNS server"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_dns_secondary",
            field=models.GenericIPAddressField(
                blank=True,
                default="8.8.4.4",
                help_text="Secondary DNS server (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_gateway",
            field=models.GenericIPAddressField(
                default="10.0.0.1",
                help_text="Default gateway IP address",
                protocol="IPv4",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_memory_mb",
            field=models.IntegerField(
                default=2048,
                help_text="Default memory allocation in MB for new LXC containers",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_subnet",
            field=models.CharField(
                default="10.0.0.0/24",
                help_text="Default subnet for container network (CIDR notation)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_swap_mb",
            field=models.IntegerField(
                default=512, help_text="Default swap size in MB for new LXC containers"
            ),
        ),
    ]
