# Generated by Django 5.0.1 on 2025-10-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_alter_application_lxc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("deploying", "Deploying"),
                    ("cloning", "Cloning"),
                    ("running", "Running"),
                    ("stopped", "Stopped"),
                    ("error", "Error"),
                    ("updating", "Updating"),
                    ("removing", "Removing"),
                ],
                db_index=True,
                default="deploying",
                max_length=50,
            ),
        ),
    ]
