# Generated by Django 5.0.1 on 2025-10-18 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxmoxHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this Proxmox host",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Hostname or IP address", max_length=255
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        default=8006,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        default="root@pam",
                        help_text="Proxmox user (e.g., root@pam)",
                        max_length=100,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Encrypted password for Proxmox API", max_length=500
                    ),
                ),
                (
                    "verify_ssl",
                    models.BooleanField(
                        default=False, help_text="Verify SSL certificate"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this host"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use as default target for deployments"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, help_text="Last successful connection", null=True
                    ),
                ),
                ("total_cpu", models.IntegerField(blank=True, null=True)),
                ("total_memory", models.BigIntegerField(blank=True, null=True)),
                ("total_storage", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proxmox_hosts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxmox Host",
                "verbose_name_plural": "Proxmox Hosts",
                "db_table": "proxmox_hosts",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProxmoxNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(default="unknown", max_length=50)),
                ("node_type", models.CharField(default="node", max_length=50)),
                ("cpu_count", models.IntegerField(blank=True, null=True)),
                ("cpu_usage", models.FloatField(blank=True, null=True)),
                ("memory_total", models.BigIntegerField(blank=True, null=True)),
                ("memory_used", models.BigIntegerField(blank=True, null=True)),
                ("storage_total", models.BigIntegerField(blank=True, null=True)),
                ("storage_used", models.BigIntegerField(blank=True, null=True)),
                ("uptime", models.BigIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("pve_version", models.CharField(blank=True, max_length=50, null=True)),
                ("lxc_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="proxmox.proxmoxhost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxmox Node",
                "verbose_name_plural": "Proxmox Nodes",
                "db_table": "proxmox_nodes",
                "unique_together": {("host", "name")},
            },
        ),
    ]
