# Generated by Django 5.0.1 on 2025-10-19 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxmox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxmoxhost",
            name="ssh_port",
            field=models.IntegerField(
                default=22,
                help_text="SSH port for pct exec commands",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="proxmoxhost",
            name="port",
            field=models.IntegerField(
                default=8006,
                help_text="Proxmox API port",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
    ]
