# Generated by Django 5.0.1 on 2025-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxmox", "0002_add_ssh_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxmoxhost",
            name="ssh_key_path",
            field=models.CharField(
                blank=True,
                help_text="Path to SSH private key for key-based authentication (optional)",
                max_length=500,
                null=True,
            ),
        ),
    ]
