# Generated by Django 5.0.1 on 2025-10-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proxmox", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("catalog_id", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                (
                    "hostname",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("deploying", "Deploying"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                            ("updating", "Updating"),
                            ("removing", "Removing"),
                        ],
                        db_index=True,
                        default="deploying",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=512, null=True)),
                ("iframe_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "public_port",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "internal_port",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                ("lxc_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "lxc_root_password",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("node", models.CharField(db_index=True, max_length=100)),
                ("config", models.JSONField(default=dict)),
                ("ports", models.JSONField(default=dict)),
                ("volumes", models.JSONField(default=list)),
                ("environment", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="proxmox.proxmoxhost",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("step", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_logs",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment Log",
                "verbose_name_plural": "Deployment Logs",
                "db_table": "deployment_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
