# Generated by Django 5.0.1 on 2025-10-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_alter_application_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="lxc_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
