# Generated by Django 5.0.1 on 2025-10-20 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_add_cloning_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="state_changed_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
