# Generated by Django 5.0.1 on 2025-10-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0005_add_state_changed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Backup filename on Proxmox storage", max_length=500
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        default="local",
                        help_text="Proxmox storage name where backup is stored",
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(blank=True, help_text="Backup size in bytes", null=True),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("snapshot", "Snapshot"),
                            ("suspend", "Suspend"),
                            ("stop", "Stop"),
                        ],
                        default="snapshot",
                        help_text="Backup mode used",
                        max_length=50,
                    ),
                ),
                (
                    "compression",
                    models.CharField(
                        choices=[
                            ("zstd", "Zstandard"),
                            ("gzip", "Gzip"),
                            ("lzo", "LZO"),
                        ],
                        default="zstd",
                        help_text="Compression algorithm",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("restoring", "Restoring"),
                            ("deleting", "Deleting"),
                        ],
                        db_index=True,
                        default="creating",
                        help_text="Current backup status",
                        max_length=50,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if backup failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When backup was initiated",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last status update"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When backup completed successfully",
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="The application this backup belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup",
                "verbose_name_plural": "Backups",
                "db_table": "backups",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "status"],
                        name="backups_applica_b46f23_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="backups_status_e51ba1_idx",
                    ),
                ],
            },
        ),
    ]
